// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],// para ejecucion de la aplicacion(ejecutad consultas) en producion o desaarrollo 
//url: process.env["DIRECT_URL"],// para desarrollo o migraciones modificaciones de la base de datos, ya que no requiere de un proxy y es mas directo
  },
});
